# This is a basic workflow to help you get started with Actions

name: Build

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: CI=false npm run build
      # - run: npm test
            - adı: Salesforce için Kaliteli Bulut Yapı Kontrolü
  # Belirli bir commit'e veya versiyona sabitleyebilirsiniz.
  # kullanımlar: qualityclouds/action-full-scan@4bc13bbfa27d8eaa0bc4978ac161d148a6f70ac4
  kullanımlar: qualityclouds/action-full-scan@1.0.1
  ile:
    # Kodunuzun kontrol edileceği Quality Clouds kuralları setini bağlamak için geçerli bir API anahtarı sağlamanız gerekir
    jeton:
    # Özellik dalı taramasını çalıştırmak için bulut modunu kullanın
    mod: # isteğe bağlı
    # Örnek kimliği. Bulut modu etkinleştirildiğinde gereklidir.
    url_id: # isteğe bağlı
    # Özellik dalı taramasını çalıştırmak için bulut modunu kullanın
    api_url: # isteğe bağlı
    # Koşu versiyonunu özelleştir
    sürüm: # isteğe bağlı
          
